[project]

name = "website"
version = "0.1.0"
description = "Personal website with Flask, blog, and portfolio."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
	"flask",
	"requests",
	"PyYAML",
	"markdown",
	"flask-sqlalchemy>=3.1.1",
	"flask-migrate>=4.1.0",
]
